Feature/kx2 be development
wolf1128/polito-se2-24-03-kiruna-explorer pull request #3
Opened 2024-11-02 10:29 UTC by simonemarcos

2024-11-02 15:27 UTC, matteovpetrera requested changes

2024-11-02 15:27 UTC, matteovpetrera commented on code/server/src/dao/documentDAO.ts
> +                const sql='INSERT INTO DocumentConnetions VALUES (?,?,?)'
typing error: should be "DocumentConnections" rather then "DocumentConnetions"

2024-11-02 15:27 UTC, matteovpetrera commented on code/server/src/dao/documentDAO.ts
> +                        reject(new DuplicateError)
distinguish types of error, it's not sure err is always a DuplicateError

2024-11-02 15:27 UTC, matteovpetrera commented on code/server/src/dao/documentDAO.ts
> +    linkDocuments(documentId1:number,documentId2:number,linkType:string): Promise<boolean> {
i would call the function createDocumentsConnection only to be more inline with the other denominations

2024-11-02 15:27 UTC, matteovpetrera commented on code/server/src/db/createDB.sql
> +DROP TABLE IF EXISTS Resouces;
typing error: "Resources" rather then "Resouces"

2024-11-02 15:27 UTC, matteovpetrera commented on code/server/src/db/createDB.sql
> +	connection TEXT NOT NULL,
i would rename connection with connectionType or linkType to fit the denomination used in other files

2024-11-02 15:27 UTC, matteovpetrera commented on code/server/src/controllers/documentController.ts
> +  async linkDocuments(documentId1:number,documentId2:number,linkType:string): Promise<boolean> {
i would suggest a simple control on the value of documentId1 and documentId2 to check if they are not the same, you did a simple check in the routes to see if the values are positives, i would add here this check only because it's easier.

2024-11-03 11:04 UTC, simonemarcos commented on code/server/src/dao/documentDAO.ts
> +    linkDocuments(documentId1:number,documentId2:number,linkType:string): Promise<boolean> {
I referenced the story action: I want to link documents

2024-11-03 11:05 UTC, simonemarcos commented on code/server/src/db/createDB.sql
> +	connection TEXT NOT NULL,
For DB schema changes Alessandro has to be notified

2024-11-03 11:33 UTC, merged